### ISSUE TITLE
Open-source checklist

### ISSUE THREAD

**Issue by conrs** [LiveRamp/typed-mutations#5]
- [x] Ensure commits are clear 
- [x] Ensure package can be published publicly
- [x] Double check license 
- [x] Polish documentation
- [x] Consider naming changes
- [x] Ensure issues are handled
- [ ] Prepare blog post 
- [ ] Make it public
